version: '3.7'

volumes:
  dbdata:

services:
  php-cli:
    build:
      context: docker/php-cli
    env_file:
      - docker/variables.env
    volumes:
      - ./:/app:delegated
    ulimits:
      nproc: 65535
      nofile:
        soft: 1048576
        hard: 1048576
